modLoader="javafml"
loaderVersion="[40,)"
license="MPL-2.0"

[[mods]]
modId="msf_friends"
version="${version}"
displayName="Minecraft Service Friends (MSF)"
logoFile=""
credits="MSF"
authors="MSF"
description="Minecraft Service Friends (MSF) — Friends + WebRTC P2P multiplayer."

[[dependencies.msf_friends]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.msf_friends]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="CLIENT"
