# Forge 1.12.2 Mod Development Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.12.2
minecraft_version_range=[1.12.2,1.13)
forge_version=14.23.5.2847
forge_version_range=[14.23.5,)
loader_version_range=[14,)
mod_id=msf_friends
mod_name=Minecraft Service Friends (MSF)
mod_license=MPL-2.0
mod_version=0.1.0
mod_group_id=dev.msf
mod_authors=MSF
mod_description=Minecraft Service Friends (MSF) — Friends + WebRTC P2P multiplayer.
