import pathlib
p = pathlib.Path(r'c:\Users\xjh37\Desktop\MSF\msf-friends-multi\settings.gradle.kts')
lines = [
    'pluginManagement {',
    '    repositories {',
    '        gradlePluginPortal()',
    '        mavenCentral()',
    '        maven { url = uri("https://maven.fabricmc.net/") }',
    '    }',
    '}',
    '',
    'dependencyResolutionManagement {',
    '    repositories {',
    '        mavenCentral()',
    '        maven { url = uri("https://maven.fabricmc.net/") }',
    '        maven { url = uri("https://libraries.minecraft.net/") }',
    '    }',
    '}',
    '',
    'rootProject.name = "MSF"',
    '',
    'include(":common")',
    'include(":versions:1.14.4:common")',
    'include(":versions:1.14.4:fabric")',
    'include(":versions:1.15.2:common")',
    'include(":versions:1.15.2:fabric")',
    'include(":versions:1.16.5:common")',
    'include(":versions:1.16.5:fabric")',
    'include(":versions:1.18.2:common")',
    'include(":versions:1.18.2:fabric")',
    'include(":versions:1.19.2:common")',
    'include(":versions:1.19.2:fabric")',
    'include(":versions:1.20.1:common")',
    'include(":versions:1.20.1:fabric")',
    'include(":versions:1.21.1:common")',
    'include(":versions:1.21.1:fabric")',
    'include(":versions:1.21.1:neoforge")',
    'include(":versions:1.21.11:common")',
    'include(":versions:1.21.11:fabric")',
    'include(":versions:1.21.11:neoforge")',
    'include(":versions:26.1.2:common")',
    'include(":versions:26.1.2:fabric")',
    'include(":versions:26.1.2:neoforge")',
    ''
]
p.write_text('\n'.join(lines), encoding='utf-8')
print(f'Written {p}, size={p.stat().st_size}')
