content = (
    'pluginManagement {\n'
    '    repositories {\n'
    '        gradlePluginPortal()\n'
    '        mavenCentral()\n'
    '        maven { url = uri("https://maven.fabricmc.net/") }\n'
    '        maven { url = uri("https://maven.neoforged.net/releases/") }\n'
    '        maven { url = uri("https://maven.minecraftforge.net/") }\n'
    '        maven { url = uri("https://repo.spongepowered.org/maven/") }\n'
    '    }\n'
    '}\n'
    '\n'
    'dependencyResolutionManagement {\n'
    '    repositories {\n'
    '        mavenCentral()\n'
    '        maven { url = uri("https://maven.fabricmc.net/") }\n'
    '        maven { url = uri("https://libraries.minecraft.net/") }\n'
    '        maven { url = uri("https://maven.minecraftforge.net/") }\n'
    '    }\n'
    '}\n'
    '\n'
    'rootProject.name = "MSF"\n'
    '\n'
    '// ---- shared pure logic (no MC dependency) ----\n'
    'include(":common")\n'
    '\n'
    '// ---- MC 1.19.2 modules ----\n'
    'include(":versions:1.19.2:common")\n'
    'include(":versions:1.19.2:forge")\n'
)
path = r'c:\Users\xjh37\Desktop\MSF\msf-friends-multi\settings.gradle.kts'
with open(path, 'w', encoding='utf-8') as f:
    f.write(content)
print(f'Written {len(content)} chars')
    '}\n'
    '\n'
    'dependencyResolutionManagement {\n'
    '    repositories {\n'
    '        mavenCentral()\n'
    '        maven { url = uri("https://maven.fabricmc.net/") }\n'
    '        maven { url = uri("https://libraries.minecraft.net/") }\n'
    '        maven { url = uri("https://maven.minecraftforge.net/") }\n'
    '    }\n'
    '}\n'
    '\n'
    'rootProject.name = "MSF"\n'
    '\n'
    '// ---- shared pure logic (no MC dependency) ----\n'
    'include(":common")\n'
    '\n'
    '// ---- MC 1.19.2 modules ----\n'
    'include(":versions:1.19.2:common")\n'
    'include(":versions:1.19.2:forge")\n'
)
path = r'c:\Users\xjh37\Desktop\MSF\msf-friends-multi\settings.gradle.kts'
with open(path, 'w', encoding='utf-8') as f:
    f.write(content)
print(f'Written {len(content)} chars')
