import os
path = os.path.join(r'c:\Users\xjh37\Desktop\MSF\msf-friends-multi', 'settings_new.gradle.kts')
lines = []
lines.append('pluginManagement {')
lines.append('    repositories {')
lines.append('        gradlePluginPortal()')
lines.append('        mavenCentral()')
lines.append('        maven { url = uri("https://maven.fabricmc.net/") }')
lines.append('        maven { url = uri("https://maven.neoforged.net/releases/") }')
lines.append('        maven { url = uri("https://maven.minecraftforge.net/") }')
lines.append('        maven { url = uri("https://repo.spongepowered.org/maven/") }')
lines.append('    }')
lines.append('}')
lines.append('')
lines.append('dependencyResolutionManagement {')
lines.append('    repositories {')
lines.append('        mavenCentral()')
lines.append('        maven { url = uri("https://maven.fabricmc.net/") }')
lines.append('        maven { url = uri("https://libraries.minecraft.net/") }')
lines.append('        maven { url = uri("https://maven.minecraftforge.net/") }')
lines.append('    }')
lines.append('}')
lines.append('')
lines.append('rootProject.name = "MSF"')
lines.append('')
lines.append('// ---- shared pure logic (no MC dependency) ----')
lines.append('include(":common")')
lines.append('')
lines.append('// ---- MC 1.19.2 modules ----')
lines.append('include(":versions:1.19.2:common")')
lines.append('include(":versions:1.19.2:forge")')
lines.append('')
content = chr(10).join(lines)
with open(path, 'w', encoding='utf-8') as f:
    f.write(content)
print('Written', len(content), 'chars to', path)